<a href="https://colab.research.google.com/github/eduardodut/projetos-algoritmos/blob/master/Projeto%201/CANA_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<b>a)</b> Realizar a leitura do arquivo de entrada em estruturas de dados apropriadas, buscando eficiência não só
no uso de memória, mas também no tempo de processamento dos algoritmos que farão uso destes dados.
(1,0 ponto)


In [1]:
#download do arquivo entrada.txt
!curl --remote-name \
    -H 'Accept: application/vnd.github.v3.raw' \
    --location https://raw.githubusercontent.com/eduardodut/projetos-algoritmos/master/Projeto%201/Dados/entrada.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.3M  100 10.3M    0     0  5029k      0  0:00:02  0:00:02 --:--:-- 5027k


In [32]:
#leitura do arquivo e inicialização das variáveis
import numpy as np
fname = '/content/entrada.txt'
dados = []
primeira_linha = []
cnt = 1
with open(fname, 'r') as file:
    
    for line in file:
      if cnt == 1:
        primeira_linha.append(line.split())
      else:
        dados.append(line.split())
        
      cnt = cnt + 1

primeira_linha = primeira_linha[0]
#inicialização das variáveis localizadas na primeira linha do arquivo
NUMERO_MESES = primeira_linha[0]
print("Número de meses compreendidos pelo arquivo: ",NUMERO_MESES)
NUMERO_FORNECEDORES = primeira_linha[1]
print("Número de fornecedores inclusos no arquivo: ",NUMERO_FORNECEDORES)
TAXA_MUDANCA_FORNECEDOR = primeira_linha[2]
print("Taxa para mudança de fornecedor: ",TAXA_MUDANCA_FORNECEDOR)
#inicialização da variável que guarda os dados do arquivo
dados = np.asarray(dados, dtype = float)
print("Número de dados de contratos: ", dados.shape[0])

Número de meses compreendidos pelo arquivo:  120
Número de fornecedores inclusos no arquivo:  100
Taxa para mudança de fornecedor:  100.0
Número de dados de contratos:  726000


In [42]:
import pandas as pd

df = pd.DataFrame(dados, columns = ['fornecedor','mes_inicial', 'mes_final', 'valor'])


fornecedor  mes_inicial  mes_final  valor
0         1.0          1.0        1.0   19.2
1         1.0          2.0        2.0   14.2
2         1.0          3.0        3.0   12.5
3         1.0          4.0        4.0   11.4
4         1.0          5.0        5.0   16.6

In [0]:
dados_fornecedor_1 = df.query(''.join(['fornecedor == 1.0'])).sort_values(['mes_inicial','mes_final'])

In [65]:
for d in dados_fornecedor_1.values:
  print(d)

Streaming output truncated to the last 5000 lines.
[  1.   21.   72.  339.1]
[  1.   21.   73.  342.7]
[  1.   21.   74.  347.6]
[  1.   21.   75.  353.8]
[  1.   21.   76.  363.2]
[  1.   21.   77.  375.1]
[  1.   21.   78.  375.9]
[  1.  21.  79. 383.]
[  1.   21.   80.  388.2]
[  1.   21.   81.  388.9]
[  1.   21.   82.  390.6]
[  1.   21.   83.  405.1]
[  1.   21.   84.  416.2]
[  1.   21.   85.  418.5]
[  1.   21.   86.  424.7]
[  1.   21.   87.  427.8]
[  1.   21.   88.  442.6]
[  1.   21.   89.  445.6]
[  1.   21.   90.  453.3]
[  1.  21.  91. 460.]
[  1.   21.   92.  464.1]
[  1.   21.   93.  474.6]
[  1.   21.   94.  480.1]
[  1.   21.   95.  480.7]
[  1.   21.   96.  486.3]
[  1.   21.   97.  494.3]
[  1.   21.   98.  506.2]
[  1.   21.   99.  512.5]
[  1.   21.  100.  517.7]
[  1.   21.  101.  529.6]
[  1.  21. 102. 538.]
[  1.   21.  103.  547.1]
[  1.   21.  104.  549.4]
[  1.   21.  105.  552.7]
[  1.   21.  106.  558.6]
[  1.   21.  107.  560.9]
[  1.   21.  108.  562.7]

In [50]:
for i in df.fornecedor.unique():
  print(i," ",df.query(''.join(['fornecedor == ',str(i)])).shape[0])

1.0   7260
2.0   7260
3.0   7260
4.0   7260
5.0   7260
6.0   7260
7.0   7260
8.0   7260
9.0   7260
10.0   7260
11.0   7260
12.0   7260
13.0   7260
14.0   7260
15.0   7260
16.0   7260
17.0   7260
18.0   7260
19.0   7260
20.0   7260
21.0   7260
22.0   7260
23.0   7260
24.0   7260
25.0   7260
26.0   7260
27.0   7260
28.0   7260
29.0   7260
30.0   7260
31.0   7260
32.0   7260
33.0   7260
34.0   7260
35.0   7260
36.0   7260
37.0   7260
38.0   7260
39.0   7260
40.0   7260
41.0   7260
42.0   7260
43.0   7260
44.0   7260
45.0   7260
46.0   7260
47.0   7260
48.0   7260
49.0   7260
50.0   7260
51.0   7260
52.0   7260
53.0   7260
54.0   7260
55.0   7260
56.0   7260
57.0   7260
58.0   7260
59.0   7260
60.0   7260
61.0   7260
62.0   7260
63.0   7260
64.0   7260
65.0   7260
66.0   7260
67.0   7260
68.0   7260
69.0   7260
70.0   7260
71.0   7260
72.0   7260
73.0   7260
74.0   7260
75.0   7260
76.0   7260
77.0   7260
78.0   7260
79.0   7260
80.0   7260
81.0   7260
82.0   7260
83.0   7260
84.0   7260
8

b) Apresentar a complexidade das estruturas utilizadas para armazenar os dados de entrada, fazendo uso
de notação assintótica e tendo como parâmetros somente a quantidade n de meses e a quantidade m de
fornecedores. (1,0 ponto)


c) Criar uma função eficiente que retorna o contrato individual, referente ao período completo de n meses,
que possui o menor valor. (1,0 ponto)


d) Apresentar a complexidade da função descrita no item anterior, fazendo uso de notação assintótica e
tendo como parâmetros somente a quantidade n de meses e a quantidade m de fornecedores. (1,0 ponto)


e) Criar uma função eficiente que retorna o contrato individual de menor valor do mercado, independente
do período a que se refere. (1,0 ponto)


f) Apresentar a complexidade da função descrita no item anterior, fazendo uso de notação assintótica e
tendo como parâmetros somente a quantidade n de meses e a quantidade m de fornecedores. (1,0 ponto)


g) Criar uma função eficiente que retorna o contrato individual, referente ao período completo de x meses
(passado como parâmetro, x ≤ n), que possui o menor valor. (1,0 ponto)


h) Apresentar a complexidade da função descrita no item anterior, fazendo uso de notação assintótica e
tendo como parâmetros somente a quantidade n de meses e a quantidade m de fornecedores. (1,0 ponto)


i) Criar um método que sugere quais contratos de energia devem ser contratados para os próximos n
meses. (1,0 ponto)


j) Apresentar a complexidade da função descrita no item anterior, fazendo uso de notação assintótica e
tendo como parâmetros somente a quantidade n de meses e a quantidade m de fornecedores. (1,0 ponto)

In [35]:
# Módulo para debug
from var_dump import var_dump

from operator import itemgetter, attrgetter

try:
    arquivo = open(fname,'r')
except FileNotFoundError:
    print('Arquivo não encontrado.')

# Função que valida o valor total do contrato
# Item A do prejeto
def valida_valor_contratos(dados, fornecedor, valor_total):

    # Variáveis usadas para localização da regra
    index = 0
    index2 = 0
    lista_contrato = []

    # Cria lista de contrados
    while (index < len(dados)):
        while (fornecedor == int(dados[index][0]) and index2 < len(dados)):
            lista_contrato.append(dados[index2])
            index2 += 1
        index += 1

    # Localiza se há divergência(s) em alguns dos contrados e o apresenta de acordo com as regras do Item A
    for l in lista_contrato:

        # Informações dos contratos realizados
        fornecedor_linha = int(l[0])
        valor_total_linha = float(l[3])

        if (fornecedor == fornecedor_linha and valor_total_linha > valor_total):
            print('Foi encontrado divergência(s) de acordo com as informações passadas nos dados que impoêm um contrato.')
            print('O contrato {con} tem obrigatoriamente valor menor ou igual aos valores dos outros contratos.\n\n' .format(con=l))

# Função que valida o somatorio dos valores total do contrato
# Item B do prejeto
def valida_somatorio_valor_contratos(dados, dados_contrato_total_meses):

    # Variáveis usadas para localização da regra
    index = 0
    lista_fornecedor = []
    lista_valor_mes = []
    valor_total_fornecedor = []

    for l in dados:

        # Informações dos contratos realizados
        fornecedor_linha = int(l[0])
        mes_inicial_linha = int(l[1])
        mes_final_linha = int(l[2])
        valor_total_linha = float(l[3])

        # Localiza valor do contrato de uma mês todo
        if (((mes_final_linha - mes_inicial_linha) == 0) or ((mes_final_linha - mes_inicial_linha) == 1)):
            lista_valor_mes.append([fornecedor_linha, valor_total_linha])
            lista_fornecedor.append(fornecedor_linha)

    # Identifica quem são os fornecedores
    lista_fornecedor = list(set(lista_fornecedor))

    # Realiza somatório de todos os fornecedores em cada mês
    while (index < len(lista_fornecedor)):

        soma = 0
        for v in lista_valor_mes:
            if (lista_fornecedor[index] == v[0]):
                soma = + soma + v[1]

        valor_total_fornecedor.append([lista_fornecedor[index], soma])

        index += 1

    # Localiza se há divergência(s) em alguns dos contrados e o apresenta de acordo com as regras do Item B
    for l in dados:

        # Informações dos contratos realizados
        fornecedor_linha = int(l[0])
        mes_inicial_linha = int(l[1])
        mes_final_linha = int(l[2])
        valor_total_linha = float(l[3])

        if (mes_inicial_linha == 1 and mes_final_linha == dados_contrato_total_meses):
            for v in valor_total_fornecedor:
                if (fornecedor_linha == v[0] and valor_total_linha > v[1]):
                    print('Foi encontrado divergência(s) de acordo com as informações passadas nos dados que impoêm um contrato.')
                    print('Os contratos do fornecedor {forn} possui um valor total de R$ {con}, ele tem obrigatoriamente do valor menor ou igual aos valores dos contratos.\n\n'.format(forn=v[0],con=v[1]))
                    print('O fornecedor possui os seguintes registros por período:')
                    print('Fornecedor: {forn} , Mês Início: {minic} , Mês Final: {mfin} , Valor: R$ {val}\n\n'.format(forn=fornecedor_linha, minic=mes_inicial_linha, mfin=mes_final_linha, val=valor_total_linha))

# Retorna o contrato individual, referente ao período completo de n meses, que possui o menor valor
def verifica_menor_contrato_periodo(dados):

    # Variáveis usadas para localização da regra
    lista_ordenada = sorted(dados, key=itemgetter(3))
    index = 0

    print('\nPeríodo completo de n meses, que possui o menor valor.')

    while (float(lista_ordenada[0][3]) == float(lista_ordenada[index][3])):
        print('O contrato de menor valor dos dados é: ' + str(lista_ordenada[index]) + '\n')
        index += 1

# Retorna o contrato individual de menor valor do mercado, independente do período a que se refere
def verifica_menor_contrato(dados):

    # Variáveis usadas para localização da regra
    lista_ordenada = sorted(dados, key=itemgetter(3))
    index = 0

    print('\nContrato individual de menor valor do mercado, independente do período a que se refere.')

    while (float(lista_ordenada[0][3]) == float(lista_ordenada[index][3])):
        print('O contrato de menor valor dos dados é: ' + str(lista_ordenada[index]) + '\n')
        index += 1

#  Retorna o contrato individual, referente ao período completo de x meses (passado como parâmetro, x ≤ n), que possui o menor valor
def verifica_menor_contrato_meses(dados):

    # Variáveis usadas para localização da regra
    lista_ordenada = sorted(dados, key=itemgetter(3))
    index = 0

    print('\nContrato individual de menor valor do mercado, independente do período a que se refere.')

    while (float(lista_ordenada[0][3]) == float(lista_ordenada[index][3])):

        print('O contrato de menor valor dos dados é: ' + str(lista_ordenada[index]) + '\n')
        index += 1

# Função que valida todas as formas de contratos
def valida_contratos(dados):

    # Informações das regras para os contratos
    dados_contrato_total_meses = int(dados[0][0])
    dados_contrato_total_fornecedor = int(dados[0][1])
    dados_contrato_total_valor = float(dados[0][2])

    dados_contrato_menor_valor_mensal = []
    dados_contrato_menor_valor_individual = []

    del dados[0]

    # Percorro todos os dados e realiza todas as validações do Item A
    for l in dados:

        # Informações dos contratos realizados
        fornecedor = int(l[0])
        mes_inicial = int(l[1])
        mes_final = int(l[2])
        valor_total = float(l[3])

        # Valida dados de todos os contratos caso haja alguma divergência nos dados
        if ((mes_inicial < 1) or (mes_inicial > dados_contrato_total_meses) or (mes_final > dados_contrato_total_meses) or (fornecedor > dados_contrato_total_meses)):

            print('Foi encontrado divergência(s) de acordo com as informações passadas nos dados que impoêm um contrato.')
            print('As regras dos contratos são esses:\n')
            print('Quantidade de Fornecedores: {forn} , Total de Meses do Contrato: {mtotal} meses , Valor do Contrato: R$ {val}\n\n' .format(forn=dados_contrato_total_fornecedor, mtotal=dados_contrato_total_meses, val=dados_contrato_total_valor))
            print('Foi encontrado problemas nas seguintes linhas abaixo:')
            print('Fornecedor: {forn} , Mês Início: {minic} , Mês Final: {mfin} , Valor: R$ {val}\n\n' .format(forn=fornecedor, minic=mes_inicial, mfin=mes_final, val=valor_total))

        # Localiza valor do contrato de uma mês todo
        elif (mes_inicial == 1 and mes_final == dados_contrato_total_meses):

            # Valida todos os contratos de acordo com valor total do período
            valida_valor_contratos(dados, fornecedor, valor_total)

            # Cria lista dos contratos por período x meses
            dados_contrato_menor_valor_mensal.append(l)

        else:
            dados_contrato_menor_valor_individual.append(l)

    # Chama função para relizar validação so somatório de todos os contratos
    valida_somatorio_valor_contratos(dados, dados_contrato_total_meses)

    # Chama função que retorna o contrato individual, referente ao período completo de n meses, que possui o menor valor
    verifica_menor_contrato_periodo(dados_contrato_menor_valor_mensal)

    # Chama função que retorna o contrato individual de menor valor do mercado, independente do período a que se refere
    verifica_menor_contrato(dados)

    # Chama função que retorna o contrato individual, referente ao período completo de x meses (passado como parâmetro, x ≤ n), que possui o menor valor
    verifica_menor_contrato_meses(dados_contrato_menor_valor_individual)


# Declaro listas para manipulação dos dados
texto = []
matriz = []

# Quebra as linhas do arquivo em vetores
texto = arquivo.readlines()

# print("vetor texto -> ",texto) # Exibe em texto
# print("")

# Esse for percorre a posições dp vetor texto
for i in range(len(texto)):
    matriz.append(texto[i].split())  # Aqui eu quebro nos espaços das palavras

# Mostra o vetor com um conjunto de vetores
# print("vetor matriz -> ", matriz)

# Mostra quedrando em linhas
# for i in range(len(texto)):
#     print(matriz[i])

valida_contratos(matriz)

# Comando para fechar o arquivo
arquivo.close()









Período completo de n meses, que possui o menor valor.
O contrato de menor valor dos dados é: ['61', '1', '120', '687.1']


Contrato individual de menor valor do mercado, independente do período a que se refere.
O contrato de menor valor dos dados é: ['8', '53', '53', '10.0']

O contrato de menor valor dos dados é: ['8', '100', '100', '10.0']

O contrato de menor valor dos dados é: ['9', '24', '24', '10.0']

O contrato de menor valor dos dados é: ['9', '30', '30', '10.0']

O contrato de menor valor dos dados é: ['11', '70', '70', '10.0']

O contrato de menor valor dos dados é: ['11', '110', '110', '10.0']

O contrato de menor valor dos dados é: ['12', '111', '111', '10.0']

O contrato de menor valor dos dados é: ['14', '27', '27', '10.0']

O contrato de menor valor dos dados é: ['15', '51', '51', '10.0']

O contrato de menor valor dos dados é: ['15', '74', '74', '10.0']

O contrato de menor valor dos dados é: ['15', '75', '75', '10.0']

O contrato de menor valor dos dados é: ['16', '6